### ISSUE TITLE
适配 Hyperf 3.1

### ISSUE THREAD

**Issue by izhengmy** [hyperf-extension/hashing#2]
@angeltxwh 大佬，如果你能看到消息，麻烦及时合并一下我最新的那个[请求](https://github.com/hyperf-extension/hashing/pull/1)。我这边针对 Hyperf 3.1 做了适配。

**Comment by angeltxwh** [comment]
不好意思，最近有些忙没来github，明天上班了立马看一下

**Comment by angeltxwh** [comment]
[8930e17](https://github.com/hyperf-extension/hashing/commit/8930e17f0f34249f8cae460198b5675a585a1d29)
